// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tscempimtjsvjijrffxk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRzY2VtcGltdGpzdmppanJmZnhrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Mzc3MjMxMTQsImV4cCI6MjA1MzI5OTExNH0.8Cxih2IYfPhfyxcb7iAm1-34mZ_5mUPrDXUSZ1-_tXs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);